# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import messenger_pb2 as messenger__pb2


class GreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/Greeter/SayHello',
        request_serializer=messenger__pb2.HelloRequest.SerializeToString,
        response_deserializer=messenger__pb2.HelloReply.FromString,
        )
    self.SayHelloAgain = channel.unary_unary(
        '/Greeter/SayHelloAgain',
        request_serializer=messenger__pb2.HelloRequest.SerializeToString,
        response_deserializer=messenger__pb2.HelloReply.FromString,
        )
    self.SayHelloAgainsecond = channel.unary_unary(
        '/Greeter/SayHelloAgainsecond',
        request_serializer=messenger__pb2.HelloRequest.SerializeToString,
        response_deserializer=messenger__pb2.HelloReply.FromString,
        )


class GreeterServicer(object):
  """The greeting service definition.
  """

  def SayHello(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayHelloAgain(self, request, context):
    """Sends another greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayHelloAgainsecond(self, request, context):
    """second client added
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=messenger__pb2.HelloRequest.FromString,
          response_serializer=messenger__pb2.HelloReply.SerializeToString,
      ),
      'SayHelloAgain': grpc.unary_unary_rpc_method_handler(
          servicer.SayHelloAgain,
          request_deserializer=messenger__pb2.HelloRequest.FromString,
          response_serializer=messenger__pb2.HelloReply.SerializeToString,
      ),
      'SayHelloAgainsecond': grpc.unary_unary_rpc_method_handler(
          servicer.SayHelloAgainsecond,
          request_deserializer=messenger__pb2.HelloRequest.FromString,
          response_serializer=messenger__pb2.HelloReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
